// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace LottieBindingTestiOS
{
	public partial class MainViewController : UIViewController
	{
		public MainViewController(IntPtr handle) : base(handle)
		{
		}

		public override void ViewDidLoad()
		{
			base.ViewDidLoad();
			var lottieLogo = new FullScreenLottieAnimationView();
			lottieLogo.DisplayLottieLoadingAnimation(this, "fdjsakl", UIColor.Blue, "coffee", 30, 30, false);
		}
	}
}
