// This file has been autogenerated from a class added in the UI designer.

namespace LottieBindingTestiOS
{
	public partial class MainViewController : UIViewController
	{
		public MainViewController(IntPtr handle) : base(handle)
		{
			
		}
	}
}
